### ISSUE TITLE
But what if even ivan is drunk on a Friday night

### ISSUE THREAD

**Issue by themoonrat** [ivanpopelyshev/pixi-legacy#1]
What happens then? Who saves the day then?

**Comment by ivanpopelyshev** [comment]
That's the thing! I don't drink, thus my down-time-window differ :)

**Comment by ivanpopelyshev** [comment]
And I dont drink exactly because I have access to servers. Either everything goes down without me, either I'll bring everything down while drunk.

**Comment by staff0rd** [comment]
@I've been on production servers both drunk and sober.  The only times I've broken a production server was when I was sober :)
